### ISSUE TITLE
Question: How do I add descriptions?

### ISSUE THREAD

**Issue by xJohnx117** [Darkhax-Minecraft/Enchantment-Descriptions#202]
I found some enchantments that don't have a proper description, and I want to add some but I can't find the correct file.

**Comment by Darkhax** [comment]
It's recommended to ask the mod developer to add the descriptions themselves so that everyone can have the descriptions. If you want custom descriptions you can add your own using a resource pack with a custom language file. The example is [here](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/1.20/common/src/main/resources/assets/enchdesc/lang/en_us.json).

**Comment by xJohnx117** [comment]
Do I need to open the mod file to find the langauge to change or add descriptions?

**Comment by Darkhax** [comment]
No, you use a resource pack.
