### ISSUE TITLE
[CRASH] Crash on start, "Could not execute entrypoint stage 'client' due to errors, provided by 'enchdesc'!"

### ISSUE THREAD

**Issue by DarianStardust** [Darkhax-Minecraft/Enchantment-Descriptions#240]
### Minecraft Version

1.20.1

### Mod Version

17.0.16

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

I press Play in the client, Client closes, shows up right away with Crash notice

### Crash Log

[crash-2024-06-06_03.00.22-client.txt](https://github.com/user-attachments/files/15604470/crash-2024-06-06_03.00.22-client.txt)

### Are you doing anything weird?

Doing some mod testing since I updated Fabric and the API's so everything is crashing, started testing from 0, installed some missing dependencies and libraries (etc), and this is the first proper Crash I can't fix on my own so far

**Comment by Darkhax** [comment]
Hello, thank you for reporting this issue. The crash is caused by the Spectrum mod and the way they are adding compatibility for Enchantment Descriptions. Please forward the crash log to them, they should know how to resolve this issue. For now, downgrade Enchantment Descriptions to the previous version.
