### ISSUE TITLE
[BUG] Duplicated Enchantment description

### ISSUE THREAD

**Issue by ffuentesm** [Darkhax-Minecraft/Enchantment-Descriptions#251]
### Minecraft Version

1.21.x

### Mod Version

21.1.1

### Mod Loader

NeoForge

### What environment are you running the mod in?

Client

### Issue Description

![image](https://github.com/user-attachments/assets/4061bec8-1f4e-418f-8235-8a2ba9aed5af)
You can see that the description is doubled. 
I am also used Apothetic Enchantments, but I don't think that is affecting things.

**Comment by Darkhax** [comment]
Hello, I am not able to recreate this issue on my end, even after installing Apothic Enchanting. Do you still have a description if you disable Enchantment Descriptions? Are there any other mods installed that may be conflicting with this?

**Comment by ffuentesm** [comment]
HUm... Seems that Farmer's delight is the cause of this. Not sure why. 
without it the tool tip works
![image](https://github.com/user-attachments/assets/ecff58d6-e13e-4482-99ef-d157363ff069)

**Comment by Darkhax** [comment]
Which version of Farmers Delight are you using? I couldn't find a 1.21.1 build so I used 1.21-1.2.4 and I am not able to recreate the issue.

**Comment by ffuentesm** [comment]
OK, I am using FarmersDelight-1.21-1.2.4, as well as these add-ons. The problem stopped when I disabled them. 
endersdelight-1.21-1.0.1, https://www.curseforge.com/minecraft/mc-mods/enders-delight
twilightdelight-3.0.0+4 https://www.curseforge.com/minecraft/mc-mods/twilights-flavors-delight

I had a similar problem with a Duplicated Tooltip on the food effects of these mods.

**Comment by Darkhax** [comment]
Thanks for narrowing it down, I can confirm the issue is with Twilight Flavors Delight. It's likely an issue with their code, but I will look into this a bit further and let you know.

**Comment by VaporeonScripts** [comment]
i got the same issue but without twilight flavor

**Comment by Darkhax** [comment]
@VaporeonScripts Can you track it down to any specific mod(s)?

**Comment by VaporeonScripts** [comment]
well idk, and i dont really need this mod as it doesnt add descriptions to some enchants, so i alr have added them through kube js

**Comment by jaredlll08** [comment]
@ffuentesm your issue is not an issue with enchantment descriptions, the mod TwilightDelight is Jar-In-Jaring another mod called L2Core, which has this piece of code that does the same thing as Enchantment Descriptions:
https://github.com/Minecraft-LightLand/L2Core/blob/main/src/main/java/dev/xkmc/l2core/events/ClientEventHandler.java#L40
so you have two mods that do the same thing.

In my opinion you should disable the config in L2Core (`configs/l2configs/l2core-client.toml`) and keep Enchantment Descriptions, as L2Core doesn't even provide enchantment descriptions for vanilla enchantments (why do they even have this feature??).

In regards to Jar-In-Jar:

You will not have the mod L2Core in your mods folder, because Jar-In-Jar is a horrible system that hides mods from users and makes debuging issues like this one a lot more tedious; however if you extract the Twilight Delight jar, and look in the `META-INF/jarjar` folder, you will find the mod there, so yes, you do have it installed.

@VaporeonScripts if you are 100% sure you don't have Twilight Delight or any other L2Core required mod (use `/neoforge mods` and see if it is printed there), then please provide a mod list (the one from that command), saying you don't need this mod and that you replaced it does absolutely nothing to get the issue fixed.

**Comment by VaporeonScripts** [comment]
I do have l2 mods,cuz of how many weaponry they add , anyways they have it to provide descriptions for their own enchants

**Comment by VaporeonScripts** [comment]
With l2 mods u mean like l2 archery ,complements,weaponry etc right ?

**Comment by jaredlll08** [comment]
I don't know the suite of L2 mods, but most likely yes. 

like I said, use the command, if you see `L2Core` anywhere in the output, you have the mod and they are duplicating the tooltip.

> anyways they have it to provide descriptions for their own enchants

If L2Core is pulling vanilla and other mods' descriptions from Enchantment Descriptions to duplicate the tooltip, then Enchantment Descriptions will be able to show descriptions for their enchantments just fine.

There is no benefit to having that config option enabled if you are using Enchantment Descriptions.

**Comment by VaporeonScripts** [comment]
Yeah,but enchantment desc mod doesn't provide support for enchantments encore,so for me it's absolutely useless xd ,anyways I will check if I got that l2 core mod later

**Comment by ffuentesm** [comment]
IT got fix in the new update
https://github.com/Minecraft-LightLand/Twilight-Delight/issues/32
