### ISSUE TITLE
[FEEDBACK] Lacking Listed Dependency

### ISSUE THREAD

**Issue by BoxieBoomkin** [Darkhax-Minecraft/Enchantment-Descriptions#263]
### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Feedback

I've installed both Enchantment Descriptions and Bookshelf, as it lists as requirement- but the game immediately crashes and states I also need "Prickle".
I have found and downloaded that too and it works but I recommend listing Prickle as a requirement / dependency on the mod page as currently, there is no mention of it anywhere.

Also request support/descriptions of Eternal Starlight enchants if possible.

**Comment by Darkhax** [comment]
Hello,

This information is already displayed on the project page for both CurseForge and Modrinth. I do not put this in the main description anymore because dependencies can change from one Minecraft version to the next, and it would be very long and complicated to read. 

As for mod support, please ask the author of Eternal Starlight to add support first. It is relatively simple and ensures users get the most accurate and up to date descriptions. If the author does not want to, or is no longer maintaining their mod we can look into adding support on our end as a last resort.

![image](https://github.com/user-attachments/assets/7d232a9c-92f4-43be-ab20-0a5116b7fee2)

![image](https://github.com/user-attachments/assets/d1af7219-c7fa-4d81-a9ef-71cc317f1de0)
