### ISSUE TITLE
Missing parts of gold armor in JEI

### ISSUE THREAD

**Issue by auboli77** [Darkhax-Minecraft/Enchantment-Descriptions#59]
Hi, I have found that parts of golden armor is missing in JEI when I add Enchantment Descriptions mod to my game. Recipies are still there, just can find them if I look at uses for gold ingot I can see them, just can't find through JEI "text" search. Missing items are golden helmet and golden leggings, I have not looked if any other items are missing.

Using:
Forge 36.1.4
EnchantmentDescriptions-1.16.5-7.0.7
Bookshelf-1.16.5-10.0.7
jei-1.16.5-7.6.4.88

**Comment by Darkhax** [comment]
Thanks for reporting this. This is fixed in [7.0.8](https://curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3285665). I left some debug code in by accident that hides the Golden Helmet, Golden Leggings, and Turtle Shell Helmet from JEI's list using their item blacklist feature. Updating the mod will restore these items in JEI.
