### ISSUE TITLE
Custom compatibility config

### ISSUE THREAD

**Issue by NixityNull** [Darkhax-Minecraft/Enchantment-Descriptions#61]
due to the endless amount of mods that add enchantments, its surely frustrating for you to get tons of compatibility questions. 

If you ad a config for descriptions of enchantments, people could simply do it themselves by adding the id file and copy-pasting a short description from the mod's page or wiki.

**Comment by Darkhax** [comment]
I actually don't get many compatibility requests/reports but I am more than happy to add descriptions when someone requests them. The majority of mods will add descriptions on their own though. 

There are a few reasons I don't want to add a config for adding new entries.

1. Custom descriptions can already be added through the resource pack system. This means that servers and modpacks already have all sorts of tools to help with this. CraftTweaker and OpenLoader are both good tools to do this depending on mc version.
2. Support for new descriptions should preferably be added by the author of the enchantment mod. This is because there are many other mods which use this same data format for descriptions. 
3. If support can not be added to the originating mod this mod should add the descriptions so the greatest number of players can benefit from that work.
