### ISSUE TITLE
only books?

### ISSUE THREAD

**Issue by koonbeast** [Darkhax-Minecraft/Enchantment-Descriptions#62]
why not leave the info under enchanted items as well? i feel like this mod fails to fulfil the purpose of helping the player know what enchantments do.

**Comment by Darkhax** [comment]
The Forge version has the `onlyEnchantedBooks` config option which is set to true by default. Fabric doesn't have configs because it's fabric.

**Comment by Wdavery** [comment]
Can you give some further explanation to this? Nearly every fabric mod I've used has config files exactly the same as the forge equivalent. 

If no config on fabric is not going to be fixed, would it be reasonable to set `onlyEnchantedBooks` to false so that the mod provides "full functionality" to fabric and forge users by default, and allow forge users to turn that to true if wanted?

**Comment by Darkhax** [comment]
@Wdavery This mod's primary target is Forge, any Fabric support is considered experimental. Unlike Forge, the Fabric API does not include a framework for config files. This means Fabric mods are required to write their own framework or use a framework written by someone else. I don't have the time to do the former right now, and there are professional considerations precluding the latter. 

Config support for Fabric may be offered in the future but it is not an active priority for me right now. As for modifying the Forge version, the mod is already defaulted to the intended user experience.

**Comment by Wdavery** [comment]
I appreciate the explanation, thank you. Totally understand your position on this. 
Supporting fabric at all is great, this mod is definitely a huge QOL upgrade for my group of players.
