### ISSUE TITLE
Suggestion: Mo'Enchantments Descriptions

### ISSUE THREAD

**Issue by Scamper10** [Darkhax-Minecraft/Enchantment-Descriptions#63]
Just a request to add support for Mo'Enchantments (https://www.curseforge.com/minecraft/mc-mods/fabric-more-enchantments).
I have posted this in their issue page too (with a link to this mod's curseforge page), as I don't know who's responsibility it is to add this.

**Comment by MickeyMouseYT** [comment]
Hello, you come to ask for support it is possible you can do it but I would like to help you unfortunately, I do not know this mod if you want to send me the description each enchanting so I can help you.

**Comment by MickeyMouseYT** [comment]
Ah yes I have not marked that there is a list and I will do it for you!

**Comment by MickeyMouseYT** [comment]
Darkhax It's ok, I made for this support but I find a bit weird for the descriptions because they are a bit messy but to you see you can modify if you want. The sites that I give you are lists of enchanting this mo'enchantment.
Have a nice night! I hope you like the enchanting description.

His list description enchantment here : https://gitlab.com/biom4st3r/moenchantments/-/blob/default/EnchantmentDescriptions.md

And his list enchantment here : https://gitlab.com/biom4st3r/moenchantments/-/blob/default/more-enchantments/src/main/resources/assets/moenchantments/lang/en_us.json

No problem 👍


[Enchant-Descriptions_Mo'Enchantments.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6689216/Enchant-Descriptions_Mo.Enchantments.zip)

**Comment by Darkhax** [comment]
Please keep this issue open until it has been fixed in the mod.

**Comment by MickeyMouseYT** [comment]
> Veuillez garder ce problème ouvert jusqu'à ce qu'il soit résolu dans le mod.

I put this file but it remains just that you can modify the descriptions that I have all given you so it's you, you check our file.

[Enchant-Descriptions_Mo'Enchantments.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6718785/Enchant-Descriptions_Mo.Enchantments.zip)

**Comment by MickeyMouseYT** [comment]
(https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/63#issuecomment-865310449)
